### PR TITLE
fix: Clean up downloaded artifact after rollback

### LINKED ISSUE #287: Rollback package not cleaned up when deploying directly to blob storage
Currently the mechanism for rolling back a function that deploys the code directly to blob storage (default behavior) is to download the blob to the `.serverless` folder and then redeploy the package. That should be cleaned up.

### PR DESCRIPTION
**Pull request by tbarlow12**
Remove the downloaded artifact from `.serverless` after deployed to service

Resolves #287

### CODE REVIEW

File: src/services/rollbackService.ts [hunk 1]
```diff
@@ -98,6 +99,9 @@ export class RollbackService extends BaseService {
     const functionAppService = new FunctionAppService(this.serverless, this.options);
     const functionApp = await functionAppService.get();
     await functionAppService.uploadZippedArfifactToFunctionApp(functionApp, artifactPath);
+    if (fs.existsSync(artifactPath)) {
```
Comment (wbreza) [inline src/services/rollbackService.ts]: Aren't we already cleaning up this folder before deployment?  Seems like we should maybe keep this around post deployment so developers can open up the zip more easily to inspect its contents??

Comment (wbreza) [reply src/services/rollbackService.ts]: Nevermind - this is after a rollback - not deployment.

Comment (mydiemho) [reply src/services/rollbackService.ts]: still think it's good to keep around even for rollback.  In case a rollback does not behave as expected, user can verify the deployed content
